[package]
name = "matchday"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3.0"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.8", features = ["derive"] }
async-trait = "0.1"
thiserror = "1.0"

[dev-dependencies]
mockito = "1.4"
